spring:
  application:
    name: ${APP_NAME:spring-configserver}
  cloud:
    active: default # use profile native if you want to use custom properties at classpath
    config:
      enabled: ${SPRING_CLOUD_CONFIG_ENABLED:true}
      server:
        git:
          # required, repo to fetch all properties
          uri: ${SPRING_CLOUD_CONFIG_SERVER_URI:}
          # optional, don't need if repo is public
          username: ${SPRING_CLOUD_CONFIG_SERVER_USERNAME:}
          # optional, don't need if repo is public
          password: ${SPRING_CLOUD_CONFIG_SERVER_PASSWORD:}
          # if true, always fetch branch 'master'
          try-master-branch: ${SPRING_CLOUD_CONFIG_SERVER_TRY_MASTER_BRANCH:false}
          # default branch to use
          default-label: ${SPRING_CLOUD_CONFIG_SERVER_DEFAULT_LABEL:main}
          # list of sub-folders from git project
          search-paths: ${SPRING_CLOUD_CONFIG_SERVER_SEARCH_PATHS:config-server*}
server:
  port: ${PORT:8080}
management:
  server:
    port: ${MANAGEMENT_PORT:8080}
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:*}
    jmx:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_JMX_EXPOSURE_INCLUDE:*}